export const RECEIVE_USER_INFO = 'receive_user_info'
export const RECEIVE_SONG_LIST = 'receive_song_list'
export const MODIFY_SONG_INDEX = 'modify_song_list'
export const MODIFY_SONG_ITEM_STATUS = 'modify_song_item_status'
export const SWITCH_SONG_ITEM_STATUS = 'switch_song_item_status'
export const UNSHIFT_USER_SONG_ITEM = 'unshift_user_song_item'
export const DELETE_USER_SONG_ITEM = 'delete_user_song_item'